import { getScoreLabel } from "@/lib/careerOps/scoreUtils";
import type { SwipeJob } from "@/types/swipe";

/**
 * Mock jobs for the swipe demo (Demo 2). Stand-in for the scraper feed.
 * Company names are well-known but treated as MOCK data — these are not real
 * current openings. Scores span all tiers so every card state is visible.
 *
 * TODO(backend): replace with real scraper output; keep the SwipeJob shape.
 */
const RAW: Omit<SwipeJob, "scoreLabel">[] = [
  {
    id: "s-001",
    company: "Vercel",
    companyLogo: "#6366f1",
    title: "Software Engineering Intern",
    location: "San Francisco, CA",
    remoteType: "hybrid",
    roleType: "internship",
    compensation: "$9,500 / month",
    source: "Scraper Feed Mock",
    score: 4.8,
    matchSummary:
      "Your Next.js projects and TypeScript depth line up almost perfectly with this team.",
    strengths: [
      "Strong React + TypeScript portfolio",
      "Shipped a Next.js App Router project",
      "Cares about developer experience",
    ],
    gaps: ["No large-scale production experience yet"],
    cautionFlags: [],
    requiredSkills: ["React", "TypeScript", "Next.js"],
    niceToHaveSkills: ["Edge runtime", "Serverless", "CI/CD"],
    tags: ["React", "TypeScript", "Next.js", "Edge"],
    description:
      "Join the framework team building tooling millions of developers rely on. Work on the Next.js App Router, edge runtime, and DX features alongside senior engineers.",
    status: "new",
    postedDate: "2026-06-18",
    applicationUrl: "https://example.com/apply/vercel-swe-intern",
  },
  {
    id: "s-002",
    company: "Stripe",
    companyLogo: "#635bff",
    title: "New Grad Software Engineer",
    location: "Seattle, WA",
    remoteType: "hybrid",
    roleType: "new_grad",
    compensation: "$145,000 + equity",
    source: "Scraper Feed Mock",
    score: 4.6,
    matchSummary:
      "Backend coursework and your payments-style capstone fit Stripe's API platform.",
    strengths: [
      "Solid data structures & algorithms",
      "Built a REST API with auth",
      "Backend internship experience",
    ],
    gaps: ["Limited Go experience"],
    cautionFlags: [],
    requiredSkills: ["APIs", "SQL", "Data structures"],
    niceToHaveSkills: ["Go", "Ruby", "Distributed systems"],
    tags: ["Go", "Ruby", "APIs", "Payments"],
    description:
      "Work on the APIs that power internet commerce. New grads rotate through backend teams owning payment flows, reliability, and developer-facing APIs.",
    status: "new",
    postedDate: "2026-06-17",
    applicationUrl: "https://example.com/apply/stripe-newgrad",
  },
  {
    id: "s-003",
    company: "Anthropic",
    companyLogo: "#d97757",
    title: "Machine Learning Intern",
    location: "San Francisco, CA",
    remoteType: "onsite",
    roleType: "internship",
    compensation: "$11,000 / month",
    source: "Scraper Feed Mock",
    score: 4.3,
    matchSummary:
      "Your ML coursework and a fine-tuning project fit the applied research track.",
    strengths: [
      "PyTorch experience from coursework",
      "Reproduced an LLM paper",
      "Strong math/stats foundation",
    ],
    gaps: ["No published research", "Limited large-scale training"],
    cautionFlags: ["Very competitive — high applicant volume"],
    requiredSkills: ["Python", "PyTorch", "ML fundamentals"],
    niceToHaveSkills: ["LLM evaluation", "Distributed training"],
    tags: ["Python", "PyTorch", "LLMs", "Research"],
    description:
      "Contribute to applied ML research on safe, steerable language models. Interns work alongside research engineers on evaluation, fine-tuning, and interpretability.",
    status: "new",
    postedDate: "2026-06-16",
    applicationUrl: "https://example.com/apply/anthropic-ml-intern",
  },
  {
    id: "s-004",
    company: "Linear",
    companyLogo: "#5e6ad2",
    title: "Frontend Engineer Intern",
    location: "Remote (US)",
    remoteType: "remote",
    roleType: "internship",
    compensation: "$8,500 / month",
    source: "Scraper Feed Mock",
    score: 4.5,
    matchSummary:
      "Your eye for polished UI and TypeScript skills match Linear's craft-focused frontend.",
    strengths: [
      "Pixel-accurate UI work",
      "TypeScript + React proficiency",
      "Performance-minded",
    ],
    gaps: ["No realtime sync engine experience"],
    cautionFlags: [],
    requiredSkills: ["React", "TypeScript", "CSS"],
    niceToHaveSkills: ["Design systems", "WebSockets", "Animation"],
    tags: ["React", "TypeScript", "Design Systems"],
    description:
      "Build the fastest project management tool on the web. Frontend interns work on the core app, design system, and famously smooth interactions.",
    status: "new",
    postedDate: "2026-06-16",
    applicationUrl: "https://example.com/apply/linear-fe-intern",
  },
  {
    id: "s-005",
    company: "Databricks",
    companyLogo: "#ff3621",
    title: "Data Science Intern",
    location: "Remote (US)",
    remoteType: "remote",
    roleType: "internship",
    compensation: "$8,800 / month",
    source: "Scraper Feed Mock",
    score: 3.9,
    matchSummary:
      "Analytics coursework and SQL fluency line up; Spark is a learnable stretch.",
    strengths: ["Strong SQL + pandas", "Built dashboards for a class project"],
    gaps: ["No Spark experience", "Light on statistics depth"],
    cautionFlags: [],
    requiredSkills: ["Python", "SQL", "Statistics"],
    niceToHaveSkills: ["Spark", "Lakehouse", "Visualization"],
    tags: ["Python", "SQL", "Spark", "Analytics"],
    description:
      "Help internal teams make data-driven decisions on the Databricks Lakehouse platform. Build models and analyses on large datasets.",
    status: "new",
    postedDate: "2026-06-15",
    applicationUrl: "https://example.com/apply/databricks-ds-intern",
  },
  {
    id: "s-006",
    company: "Ramp",
    companyLogo: "#f6e04b",
    title: "Backend Engineer, New Grad",
    location: "New York, NY",
    remoteType: "onsite",
    roleType: "new_grad",
    compensation: "$150,000 + equity",
    source: "Scraper Feed Mock",
    score: 4.1,
    matchSummary:
      "Backend internship plus Python depth fit Ramp's services; fintech domain is new.",
    strengths: [
      "Backend internship experience",
      "Strong Python and SQL",
      "Owned a service end to end",
    ],
    gaps: ["No fintech / ledger domain knowledge"],
    cautionFlags: [],
    requiredSkills: ["Python", "PostgreSQL", "APIs"],
    niceToHaveSkills: ["Ledgers", "Payments", "Event-driven systems"],
    tags: ["Python", "PostgreSQL", "Fintech"],
    description:
      "Build the financial backbone behind Ramp's spend management platform. Own services for payments, ledgers, and integrations.",
    status: "new",
    postedDate: "2026-06-15",
    applicationUrl: "https://example.com/apply/ramp-backend",
  },
  {
    id: "s-007",
    company: "Perplexity",
    companyLogo: "#20808d",
    title: "AI Engineer Intern",
    location: "San Francisco, CA",
    remoteType: "onsite",
    roleType: "internship",
    compensation: "$10,000 / month",
    source: "Scraper Feed Mock",
    score: 4.4,
    matchSummary:
      "Your RAG side project and prompt-engineering work fit applied AI engineering.",
    strengths: [
      "Built a RAG app with embeddings",
      "Comfortable with LLM APIs",
      "Ships fast, iterates on prompts",
    ],
    gaps: ["Limited production inference/scaling experience"],
    cautionFlags: [],
    requiredSkills: ["Python", "LLM APIs", "RAG"],
    niceToHaveSkills: ["Vector DBs", "Ranking", "Search"],
    tags: ["Python", "LLMs", "RAG", "Search"],
    description:
      "Build the answer engine. Work on retrieval, ranking, and LLM orchestration that powers Perplexity's search experience.",
    status: "new",
    postedDate: "2026-06-14",
    applicationUrl: "https://example.com/apply/perplexity-ai-intern",
  },
  {
    id: "s-008",
    company: "Notion",
    companyLogo: "#0f0f0f",
    title: "Full Stack Engineer, New Grad",
    location: "New York, NY",
    remoteType: "hybrid",
    roleType: "new_grad",
    compensation: "$135,000 + equity",
    source: "Scraper Feed Mock",
    score: 3.7,
    matchSummary:
      "Full-stack project work fits; you'll ramp on their scale and data model.",
    strengths: ["Built full-stack apps end to end", "Comfortable React + Node"],
    gaps: ["No experience with very large relational schemas"],
    cautionFlags: [],
    requiredSkills: ["React", "Node.js", "PostgreSQL"],
    niceToHaveSkills: ["TypeScript", "Realtime collaboration"],
    tags: ["React", "Node.js", "PostgreSQL"],
    description:
      "Work across the stack on the connected workspace used by millions. Own features touching the editor, databases, and collaboration.",
    status: "new",
    postedDate: "2026-06-14",
    applicationUrl: "https://example.com/apply/notion-fullstack",
  },
  {
    id: "s-009",
    company: "Datadog",
    companyLogo: "#632ca6",
    title: "Platform Engineering Intern",
    location: "Boston, MA",
    remoteType: "hybrid",
    roleType: "internship",
    compensation: "$8,700 / month",
    source: "Scraper Feed Mock",
    score: 3.6,
    matchSummary:
      "Systems coursework fits; you'll ramp on Go and large-scale observability.",
    strengths: ["OS & networking coursework", "Docker / Kubernetes exposure"],
    gaps: ["No Go experience", "New to observability domain"],
    cautionFlags: [],
    requiredSkills: ["Linux", "Containers", "Networking"],
    niceToHaveSkills: ["Go", "Kubernetes", "Observability"],
    tags: ["Go", "Kubernetes", "Platform"],
    description:
      "Build the monitoring platform engineering teams trust. Join teams owning data pipelines, agents, and product surfaces at scale.",
    status: "new",
    postedDate: "2026-06-13",
    applicationUrl: "https://example.com/apply/datadog-platform-intern",
  },
  {
    id: "s-010",
    company: "Cloudflare",
    companyLogo: "#f38020",
    title: "Cloud Engineering Intern",
    location: "Austin, TX",
    remoteType: "hybrid",
    roleType: "internship",
    compensation: "$8,400 / month",
    source: "Scraper Feed Mock",
    score: 3.8,
    matchSummary:
      "Networking fundamentals and a cloud project make this a solid fit.",
    strengths: ["Networking fundamentals", "Built a project on a cloud provider"],
    gaps: ["No edge computing experience"],
    cautionFlags: [],
    requiredSkills: ["Networking", "Linux", "Cloud basics"],
    niceToHaveSkills: ["Edge computing", "Rust", "WASM"],
    tags: ["Cloud", "Networking", "Edge"],
    description:
      "Help run the network that powers a large share of the internet. Work on edge services, performance, and reliability.",
    status: "new",
    postedDate: "2026-06-13",
    applicationUrl: "https://example.com/apply/cloudflare-cloud-intern",
  },
  {
    id: "s-011",
    company: "CrowdStrike",
    companyLogo: "#fc0000",
    title: "Security Engineering Intern",
    location: "Remote (US)",
    remoteType: "remote",
    roleType: "internship",
    compensation: "$8,600 / month",
    source: "Scraper Feed Mock",
    score: 3.3,
    matchSummary:
      "Security electives help, but the role expects more hands-on tooling.",
    strengths: ["Security electives", "Comfortable scripting in Python"],
    gaps: ["Limited hands-on security tooling", "No detection engineering work"],
    cautionFlags: ["Requirements lean toward prior security experience"],
    requiredSkills: ["Python", "Security fundamentals"],
    niceToHaveSkills: ["Detection engineering", "Threat intel", "EDR"],
    tags: ["Security", "Python", "Detection"],
    description:
      "Support the platform that stops breaches. Build tooling and detections used across a global security cloud.",
    status: "new",
    postedDate: "2026-06-12",
    applicationUrl: "https://example.com/apply/crowdstrike-sec-intern",
  },
  {
    id: "s-012",
    company: "Figma",
    companyLogo: "#a259ff",
    title: "Software Engineering Intern",
    location: "San Francisco, CA",
    remoteType: "hybrid",
    roleType: "internship",
    compensation: "$9,200 / month",
    source: "Scraper Feed Mock",
    score: 3.4,
    matchSummary:
      "Web fundamentals are there, but the graphics/C++ rendering work is a gap.",
    strengths: ["Strong web fundamentals", "TypeScript experience"],
    gaps: ["No C++ or graphics experience", "Unfamiliar with WebGL"],
    cautionFlags: ["Role leans heavily on graphics/systems background"],
    requiredSkills: ["TypeScript", "Web fundamentals"],
    niceToHaveSkills: ["C++", "WebGL", "Rendering pipelines"],
    tags: ["C++", "WebGL", "Graphics"],
    description:
      "Work on the multiplayer design tool used by product teams everywhere. This team focuses on the high-performance rendering engine.",
    status: "new",
    postedDate: "2026-06-12",
    applicationUrl: "https://example.com/apply/figma-swe-intern",
  },
  {
    id: "s-013",
    company: "Snowflake",
    companyLogo: "#29b5e8",
    title: "Backend Engineer, New Grad",
    location: "San Mateo, CA",
    remoteType: "onsite",
    roleType: "new_grad",
    compensation: "$140,000 + equity",
    source: "Scraper Feed Mock",
    score: 4.0,
    matchSummary:
      "Database coursework and Java skills fit the data platform backend well.",
    strengths: ["Databases coursework", "Solid Java", "Internship experience"],
    gaps: ["No distributed query engine experience"],
    cautionFlags: [],
    requiredSkills: ["Java", "SQL", "Data structures"],
    niceToHaveSkills: ["Distributed systems", "Query optimization"],
    tags: ["Java", "Databases", "Distributed Systems"],
    description:
      "Build the data cloud. New grads own services across storage, query processing, and platform reliability.",
    status: "new",
    postedDate: "2026-06-11",
    applicationUrl: "https://example.com/apply/snowflake-backend",
  },
  {
    id: "s-014",
    company: "Scale AI",
    companyLogo: "#5a2dd6",
    title: "Machine Learning Intern",
    location: "San Francisco, CA",
    remoteType: "onsite",
    roleType: "internship",
    compensation: "$9,000 / month",
    source: "Scraper Feed Mock",
    score: 2.8,
    matchSummary:
      "Some ML exposure, but the role expects stronger MLOps and pipeline depth.",
    strengths: ["Python proficiency", "Intro ML coursework"],
    gaps: ["No MLOps / pipeline experience", "Limited model deployment"],
    cautionFlags: ["Role expects more applied ML maturity than profile shows"],
    requiredSkills: ["Python", "ML fundamentals"],
    niceToHaveSkills: ["MLOps", "Data pipelines", "Airflow"],
    tags: ["Python", "ML Ops", "Pipelines"],
    description:
      "Support the data engine behind frontier AI models. Build tooling and pipelines for large-scale data labeling and evaluation.",
    status: "new",
    postedDate: "2026-06-10",
    applicationUrl: "https://example.com/apply/scale-ml-intern",
  },
  {
    id: "s-015",
    company: "Plaid",
    companyLogo: "#000000",
    title: "Product Engineer, New Grad",
    location: "Remote (US)",
    remoteType: "remote",
    roleType: "new_grad",
    compensation: "$138,000 + equity",
    source: "Scraper Feed Mock",
    score: 4.2,
    matchSummary:
      "Your product-minded full-stack projects fit this customer-facing eng role.",
    strengths: [
      "Full-stack project experience",
      "Product sense from a hackathon win",
      "Ships polished features",
    ],
    gaps: ["No fintech integration experience"],
    cautionFlags: [],
    requiredSkills: ["TypeScript", "React", "APIs"],
    niceToHaveSkills: ["Fintech", "Product analytics"],
    tags: ["TypeScript", "React", "Product"],
    description:
      "Build the connective tissue of fintech. Product engineers own customer-facing features end to end, from API to UI.",
    status: "new",
    postedDate: "2026-06-10",
    applicationUrl: "https://example.com/apply/plaid-product-eng",
  },
  {
    id: "s-016",
    company: "Brex",
    companyLogo: "#f46a35",
    title: "Frontend Engineer Intern",
    location: "Remote (US)",
    remoteType: "remote",
    roleType: "internship",
    source: "Scraper Feed Mock",
    score: 2.3,
    matchSummary:
      "Frontend basics overlap, but the posting reads senior and comp is unlisted.",
    strengths: ["React fundamentals"],
    gaps: [
      "No GraphQL experience",
      "Posting expects more autonomy than an intern profile",
    ],
    cautionFlags: ["Compensation not listed", "Reads above intern level"],
    requiredSkills: ["React", "GraphQL"],
    niceToHaveSkills: ["Apollo", "Design systems"],
    tags: ["React", "GraphQL", "Fintech"],
    description:
      "Work on the frontend of Brex's financial platform for startups. This posting emphasizes ownership of complex GraphQL-driven surfaces.",
    status: "new",
    postedDate: "2026-06-09",
    applicationUrl: "https://example.com/apply/brex-fe-intern",
  },
];

export const MOCK_SWIPE_JOBS: SwipeJob[] = RAW.map((j) => ({
  ...j,
  scoreLabel: getScoreLabel(j.score),
}));
